apiVersion: v1
kind: ConfigMap
metadata:
  name: config-observability
  namespace: knative-serving
data:
  # metrics-protocol field specifies the protocol used when exporting metrics
  # It supports either 'none' (the default), 'prometheus', 'http/protobuf' (OTLP HTTP), 'grpc' (OTLP gRPC)
  metrics-protocol: prometheus

  tracing-protocol:      http/protobuf
  tracing-endpoint:      http://jaeger-collector.observability.svc:4318/v1/traces
  tracing-sampling-rate: "1"