apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  workloads:
    - name: activator
      replicas: 2
    - name: net-kourier-controller
      replicas: 2
  ingress:
    kourier:
      enabled: true
      http-port: 30080
      service-type: NodePort
  config:
    network:
      ingress-class: "kourier.ingress.networking.knative.dev"
      domain-template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
    domain:
      knative.qpid.jp: ""

