apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/sundaypeople/k8s-manifest
    targetRevision: HEAD
    path: applications/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: target-namespace
