apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sundaypeople/k8s-manifest
    targetRevision: HEAD
    path: opentelemetry/
  destination:
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - ServerSideApply=true
