namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

patches:
  - target:
      version: v1
      kind: ConfigMap
      name: argocd-cm
    path: argocd-cm-patch.yml