
helmCharts:
  - name: opentelemetry-collector
    repo: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.157.0
    releaseName: opentelemetry
    namespace: opentelemetry
    valuesInline:
      image:
        repository: otel/opentelemetry-collector-k8s