mode: daemonset
serviceAccount:
  name: "collector"
  create: false
image:
  repository: "soyokaze0125/my-otel-collector"
  pullPolicy: Always
presets:
  logsCollection:
    enabled: false
  hostMetrics:
    enabled: false
  kubernetesAttributes:
    enabled: false
  kubeletMetrics:
    enabled: false
  clusterMetrics:
    enabled: false
extraEnvsFrom:
  - secretRef:
      name: ms-token-delta
ports:
  otlp:
    enabled: false
  otlp-http:
    enabled: false
  jaeger-compact:
    enabled: false
  jaeger-grpc:
    enabled: false
  jaeger-thrift:
    enabled: false
  zipkin:
    enabled: false

config:
  receivers:
    prometheus:
      config:
        scrape_configs:
          - job_name: 'knative'
            scrape_interval: 30s
            kubernetes_sd_configs:
              - role: pod
                namespaces:
                  names:
                    - knative-serving
            relabel_configs:
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - source_labels: [ __meta_kubernetes_pod_container_port_name ]
                regex: metrics
                action: keep
            metric_relabel_configs:
              - source_labels: [ __name__ ]
                regex: http_client_request_duration_seconds_.*
                action: keep

    # ★ 2. ラベルが消えて合算されたデータに対して、自作のZigZagで再起動スパイクを防止
  processors:
    zigzag:
      drop_labels:
        # Prometheus receiver由来の可能性があるもの
        - "pod"
        - "instance"
        - "pod_template_hash"

        # OTel Resource Attributes
        - "k8s.container.name"
        - "k8s.node.name"
        - "k8s.pod.name"
        - "k8s.pod.uid"
        - "k8s.replicaset.name"

        - "service.instance.id"
        - "service.name"

        - "server.address"
        - "server.port"
        - "url.scheme"

        # 元々のPrometheusラベル
        - "kn_configuration_name"
        - "app"
        - "app_kubernetes_io_component"
        - "app_kubernetes_io_name"
        - "app_kubernetes_io_version"
        - "otel_scope_name"
        - "otel_scope_version"
        - "namespace"
        - "network_protocol_name"
        - "network_protocol_version"
        - "role"
      output_suffix: "_materialized"
      state_expiry: 5m

    transform:
      metric_statements:
        - context: metric
          statements:
            # "old_metric_name" を "new_metric_name" に変更する
            - set(name, "delta_http_client_request_duration_seconds") where name == "http_client_request_duration_seconds"
            - set(name, "delta_http_client_request_duration_seconds_materialized") where name == "http_client_request_duration_seconds_materialized"


    batch:
      timeout: 10s
      send_batch_size: 1024

  exporters:
    debug:
      verbosity: detailed
    prometheusremotewrite/sacloud:
      endpoint: "https://113801787278.metrics.monitoring.global.api.sacloud.jp/prometheus/api/v1/write"
      headers:
        Authorization: "Bearer ${TOKEN}"
    prometheusremotewrite/local:
      endpoint: "http://prometheus.prometheus.svc.cluster.local:9090/api/v1/write"
      tls:
        insecure: true

  service:
    telemetry:
      logs:
        level: debug
    pipelines:
      metrics:
        receivers: [prometheus]
        processors: [ zigzag, batch]
        exporters: [prometheusremotewrite/local, prometheusremotewrite/sacloud]