mode: daemonset
serviceAccount:
  name: "collector"
  create: false
image:
  repository: "otel/opentelemetry-collector-contrib"

extraEnvsFrom:
  - secretRef:
      name: ms-token
ports:
  otlp:
    enabled: false
  otlp-http:
    enabled: false
  jaeger-compact:
    enabled: false
  jaeger-grpc:
    enabled: false
  jaeger-thrift:
    enabled: false
  zipkin:
    enabled: false

config:
  receivers:
    prometheus:
      config:
        scrape_configs:
          - job_name: 'knative'
            scrape_interval: 30s
            kubernetes_sd_configs:
              - role: pod
                namespaces:
                  names:
                    - knative-serving
            relabel_configs:
              - action: labelmap
                regex: __meta_kubernetes_pod_label_(.+)
              - source_labels: [ __meta_kubernetes_pod_container_port_name ]
                regex: metrics
                action: keep
            metric_relabel_configs:
              - source_labels: [ __name__ ]
                regex: http_client_request_duration_seconds_.*
                action: keep
  processors:
    # 1. まず累積カウンターを差分（Delta）に変換し、状態を管理する
#    cumulativetodelta:

    # 2. 差分（Delta）になった状態でラベルを削除し、合算する
    transform:
      metric_statements:
        - context: metric
          statements:
            # "old_metric_name" を "new_metric_name" に変更する
            - set(name, "delta_http_client_request_duration_seconds") where name == "http_client_request_duration_seconds"
#        - context: datapoint
#          statements:
#            - delete_key(attributes, "instance")
#            - delete_key(attributes, "pod")
#            - delete_key(attributes, "pod_template_hash")
#            - delete_key(attributes, "kn_revision_name")
#
#        - context: metric
#          statements:
#            - aggregate_on_attributes("sum") where type == "Sum"

  exporters:
    debug:
      verbosity: detailed
    prometheusremotewrite:
      endpoint: "https://113801781482.metrics.monitoring.global.api.sacloud.jp/prometheus/api/v1/write"
      headers:
        Authorization: "Bearer ${TOKEN}" # 環境変数を使用

  service:
    pipelines:
      metrics:
        receivers: [ prometheus ]
        processors: [transform]
        exporters: [  prometheusremotewrite,debug ]